# This is a basic workflow that is manually triggered

name: artsakh Pi

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, pull_request]


# This workflow makes a 64 bit Raspberry Pi Ubuntu Server Image.
# It does not have the security issues mentioned here: https://github.com/tendermint/tendermint/blob/master/docs/tendermint-core/running-in-production.md#validator-signing-on-32-bit-architectures-or-arm
# Later, more devices will be supported, as well.


jobs:
  build:
    name: artsakh Pi Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out artsakh
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.15

      - name: Compile artsakh
        run: |
            cd cmd/artsakhd
            go build .
            cd ..
            cd artsakhcli
            go build .
        env:
          GOOS: linux
          GOARCH: arm64

      - name: Upload artsakh Arm64 CLI
        uses: actions/upload-artifact@v2
        with:
          name: artsakhcli arm64
          path: cmd/artsakhcli/artsakhcli

      - name: Upload artsakh Arm64 daemon
        uses: actions/upload-artifact@v2
        with:
          name: artsakhd arm64
          path: cmd/artsakhd/artsakhd

      - name: Build artsakh.img
        run: docker run --rm --privileged -v /dev:/dev -v ${PWD}:/build mkaczanowski/packer-builder-arm build .pi/pibuild.json

      - name: Install PiShrink
        run: |
          wget https://raw.githubusercontent.com/Drewsif/PiShrink/master/pishrink.sh
          chmod +x pishrink.sh
          sudo mv pishrink.sh /usr/local/bin

      - name: Shrink artsakh.img
        run: sudo pishrink.sh -a -Z -v artsakh.img

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artsakh PI
          path: artsakh.img.xz
